-- Add example source URL columns to flashcards table
ALTER TABLE public.flashcards 
ADD COLUMN IF NOT EXISTS example_source_1 text,
ADD COLUMN IF NOT EXISTS example_source_2 text,
ADD COLUMN IF NOT EXISTS example_source_3 text;

-- Insert 10 test flashcards with comprehensive data
INSERT INTO public.flashcards (
  front, 
  back,
  phonetic,
  english_definition,
  chinese_definition,
  image_url,
  synonyms,
  antonyms,
  related_words,
  example_sentence_1,
  example_translation_1,
  example_source_1,
  example_sentence_2,
  example_translation_2,
  example_source_2
) VALUES
(
  'serendipity',
  '意外發現珍奇事物的運氣',
  '/ˌserənˈdɪpɪti/',
  'The occurrence of events by chance in a happy or beneficial way',
  '意外發現珍奇事物的運氣；偶然發現的幸運',
  'https://images.unsplash.com/photo-1518709268805-4e9042af9f23',
  ARRAY['luck', 'fortune', 'chance'],
  ARRAY['misfortune', 'bad luck'],
  ARRAY['coincidence', 'fate', 'destiny'],
  'Their meeting was pure serendipity, leading to a lifelong friendship.',
  '他們的相遇純屬偶然，卻促成了一生的友誼。',
  'https://www.oxfordlearnersdictionaries.com/definition/english/serendipity',
  'The discovery of penicillin was a case of serendipity in scientific research.',
  '盤尼西林的發現是科學研究中一個意外收穫的案例。',
  'https://www.merriam-webster.com/dictionary/serendipity'
),
(
  'ephemeral',
  '短暫的',
  '/ɪˈfemərəl/',
  'Lasting for a very short time',
  '短暫的；瞬息的',
  'https://images.unsplash.com/photo-1490730141103-6cac27aaab94',
  ARRAY['temporary', 'fleeting', 'transient'],
  ARRAY['permanent', 'lasting', 'enduring'],
  ARRAY['momentary', 'brief', 'short-lived'],
  'The beauty of cherry blossoms is ephemeral, lasting only a few weeks.',
  '櫻花之美是短暫的，只持續幾週。',
  'https://dictionary.cambridge.org/dictionary/english/ephemeral',
  'Social media trends are often ephemeral, disappearing as quickly as they arise.',
  '社交媒體趨勢往往是短暫的，來得快去得也快。',
  'https://www.vocabulary.com/dictionary/ephemeral'
),
(
  'resilience',
  '恢復力',
  '/rɪˈzɪliəns/',
  'The capacity to recover quickly from difficulties',
  '恢復力；復原力；韌性',
  'https://images.unsplash.com/photo-1518895949257-7621c3c786d7',
  ARRAY['toughness', 'strength', 'flexibility'],
  ARRAY['weakness', 'fragility'],
  ARRAY['endurance', 'stamina', 'perseverance'],
  'Her resilience helped her overcome numerous challenges in life.',
  '她的復原力幫助她克服了生活中的無數挑戰。',
  'https://www.psychologytoday.com/intl/basics/resilience',
  'Building resilience is essential for mental health and well-being.',
  '建立復原力對心理健康和幸福感至關重要。',
  'https://www.apa.org/topics/resilience'
),
(
  'ambiguous',
  '模稜兩可的',
  '/æmˈbɪɡjuəs/',
  'Open to more than one interpretation; not having one obvious meaning',
  '模稜兩可的；含糊不清的',
  'https://images.unsplash.com/photo-1518709268805-4e9042af9f23',
  ARRAY['unclear', 'vague', 'uncertain'],
  ARRAY['clear', 'obvious', 'unambiguous'],
  ARRAY['equivocal', 'cryptic', 'obscure'],
  'His ambiguous answer left everyone confused about his true intentions.',
  '他模稜兩可的回答讓大家對他的真實意圖感到困惑。',
  'https://www.britannica.com/dictionary/ambiguous',
  'The contract language was deliberately ambiguous to allow for flexibility.',
  '合約語言刻意含糊不清，以便保持靈活性。',
  'https://legal-dictionary.thefreedictionary.com/ambiguous'
),
(
  'ubiquitous',
  '無所不在的',
  '/juːˈbɪkwɪtəs/',
  'Present, appearing, or found everywhere',
  '無所不在的；普遍存在的',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71',
  ARRAY['omnipresent', 'pervasive', 'universal'],
  ARRAY['rare', 'scarce', 'uncommon'],
  ARRAY['widespread', 'prevalent', 'common'],
  'Smartphones have become ubiquitous in modern society.',
  '智慧型手機在現代社會已經無所不在。',
  'https://www.collinsdictionary.com/dictionary/english/ubiquitous',
  'The ubiquitous presence of social media affects how we communicate.',
  '社交媒體無所不在的存在影響了我們的溝通方式。',
  'https://www.macmillandictionary.com/dictionary/british/ubiquitous'
),
(
  'pragmatic',
  '務實的',
  '/præɡˈmætɪk/',
  'Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations',
  '務實的；實際的；講求實效的',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40',
  ARRAY['practical', 'realistic', 'sensible'],
  ARRAY['idealistic', 'impractical', 'unrealistic'],
  ARRAY['matter-of-fact', 'down-to-earth', 'businesslike'],
  'We need to take a pragmatic approach to solving this problem.',
  '我們需要採取務實的方法來解決這個問題。',
  'https://www.ldoceonline.com/dictionary/pragmatic',
  'His pragmatic decision-making style helped the company navigate difficult times.',
  '他務實的決策風格幫助公司度過了艱難時期。',
  'https://www.businessdictionary.com/definition/pragmatic.html'
),
(
  'eloquent',
  '雄辯的',
  '/ˈeləkwənt/',
  'Fluent or persuasive in speaking or writing',
  '雄辯的；有說服力的；口才流利的',
  'https://images.unsplash.com/photo-1475721027785-f74eccf877e2',
  ARRAY['articulate', 'fluent', 'persuasive'],
  ARRAY['inarticulate', 'tongue-tied', 'hesitant'],
  ARRAY['expressive', 'silver-tongued', 'well-spoken'],
  'Her eloquent speech moved the audience to tears.',
  '她雄辯的演講讓觀眾感動落淚。',
  'https://www.thesaurus.com/browse/eloquent',
  'Martin Luther King Jr. was known for his eloquent advocacy for civil rights.',
  '馬丁·路德·金以其為民權雄辯的倡導而聞名。',
  'https://www.biography.com/activist/martin-luther-king-jr'
),
(
  'meticulous',
  '一絲不苟的',
  '/məˈtɪkjələs/',
  'Showing great attention to detail; very careful and precise',
  '一絲不苟的；極仔細的；精確的',
  'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b',
  ARRAY['careful', 'precise', 'thorough'],
  ARRAY['careless', 'sloppy', 'negligent'],
  ARRAY['painstaking', 'scrupulous', 'fastidious'],
  'The architect was meticulous in planning every detail of the building.',
  '建築師在規劃建築的每個細節時都一絲不苟。',
  'https://www.wordreference.com/definition/meticulous',
  'Her meticulous research ensured the accuracy of the scientific paper.',
  '她一絲不苟的研究確保了科學論文的準確性。',
  'https://www.nature.com/articles/d41586-019-02918-5'
),
(
  'innovative',
  '創新的',
  '/ˈɪnəveɪtɪv/',
  'Featuring new methods; advanced and original',
  '創新的；革新的；新穎的',
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c',
  ARRAY['creative', 'original', 'inventive'],
  ARRAY['conventional', 'traditional', 'unoriginal'],
  ARRAY['groundbreaking', 'pioneering', 'novel'],
  'The company is known for its innovative products and solutions.',
  '該公司以其創新的產品和解決方案而聞名。',
  'https://hbr.org/topic/innovation',
  'Innovative thinking is crucial for business success in the digital age.',
  '在數位時代，創新思維對企業成功至關重要。',
  'https://www.forbes.com/innovation/'
),
(
  'benevolent',
  '仁慈的',
  '/bəˈnevələnt/',
  'Well meaning and kindly; serving a charitable rather than a profit-making purpose',
  '仁慈的；善意的；慈善的',
  'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b',
  ARRAY['kind', 'generous', 'charitable'],
  ARRAY['malevolent', 'cruel', 'unkind'],
  ARRAY['compassionate', 'philanthropic', 'altruistic'],
  'The benevolent donor gave millions to support education.',
  '這位仁慈的捐贈者捐贈了數百萬來支持教育。',
  'https://www.vocabulary.com/dictionary/benevolent',
  'Her benevolent nature made her beloved by everyone in the community.',
  '她仁慈的天性使她受到社區中每個人的愛戴。',
  'https://www.goodreads.com/quotes/tag/benevolence'
);